public enum AnalysisEvent: Sendable {
    case analysisStarted(AnalysisStartedInfo)
    case analysisFinished(AnalysisFinishedInfo)
    case progressUpdate(ProgressInfo)
    case sweepPointStarted(SweepPointInfo)
    case sweepPointFinished(SweepPointResultInfo)
    case newtonIterationStarted(NewtonInfo)
    case newtonIterationFinished(NewtonResultInfo)
    case newtonConvergenceFailure(NewtonFailureInfo)
    case timeStepCompleted(TimeStepInfo)
    case timeStepRejected(TimeStepRejectInfo)
    case gpuDispatchStarted(GPUDispatchInfo)
    case gpuDispatchFinished(GPUDispatchResultInfo)
    case metricSample(MetricSampleInfo)
    case warning(DiagnosticInfo)
    case error(DiagnosticInfo)
}
